services:
  - type: web
    name: pdf-extractor-app
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y tesseract-ocr poppler-utils && \
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DEEPSEEK_API_KEY
        sync: false
